-- MySQL Script generated by MySQL Workbench
-- 01/31/18 07:00:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cine_colombia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cine_colombia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine_colombia` DEFAULT CHARACTER SET utf8 ;
USE `cine_colombia` ;

-- -----------------------------------------------------
-- Table `cine_colombia`.`Cartelera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_colombia`.`Cartelera` (
  `Nombre_Pelicula` VARCHAR(45) NOT NULL,
  `Descripcion_Pelicula` VARCHAR(45) NOT NULL,
  `Duracion_Peicula` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Nombre_Pelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine_colombia`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_colombia`.`Rol` (
  `Cod_Rol` VARCHAR(45) NOT NULL COMMENT 'Nombre el rol',
  `Desc_Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine_colombia`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_colombia`.`Persona` (
  `Nombre_Usuario` INT NOT NULL COMMENT 'Nombre con el que el cliente se resgistra ',
  `Rol_Cod_Rol` VARCHAR(45) NOT NULL,
  `Nombre_Persona` VARCHAR(45) NOT NULL COMMENT 'Nombre de la persona',
  `Apellido_Persona` VARCHAR(45) NOT NULL COMMENT 'Apellido con el esta registrada lapersona',
  `contrasena` VARCHAR(500) NOT NULL,
  `Cantidad_puntos` INT NULL DEFAULT NULL COMMENT 'cantidad de puntos que acumula el cliente',
  PRIMARY KEY (`Nombre_Usuario`, `Rol_Cod_Rol`),
  INDEX `fk_Persona_Rol1_idx` (`Rol_Cod_Rol` ASC),
  CONSTRAINT `fk_Persona_Rol1`
    FOREIGN KEY (`Rol_Cod_Rol`)
    REFERENCES `cine_colombia`.`Rol` (`Cod_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine_colombia`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_colombia`.`Sala` (
  `Numero_Sala` INT NOT NULL,
  `Cantidad_Entradas` INT NOT NULL,
  PRIMARY KEY (`Numero_Sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine_colombia`.`Boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine_colombia`.`Boleta` (
  `Numero_Boleta` INT NOT NULL,
  `Cliente_Documento_Cliente` INT NOT NULL,
  `Cartelera_Nombre_Pelicula` VARCHAR(45) NOT NULL,
  `Sala_Numero_Sala` INT NOT NULL,
  `Numero_Sala` INT NOT NULL,
  `Letra_Asiento` VARCHAR(45) NOT NULL,
  `Numero_Columna_Asiento` INT NOT NULL,
  PRIMARY KEY (`Numero_Boleta`),
  INDEX `fk_Boleta_Cliente_idx` (`Cliente_Documento_Cliente` ASC),
  INDEX `fk_Boleta_Cartelera1_idx` (`Cartelera_Nombre_Pelicula` ASC),
  INDEX `fk_Boleta_Sala1_idx` (`Sala_Numero_Sala` ASC),
  CONSTRAINT `fk_Boleta_Cliente`
    FOREIGN KEY (`Cliente_Documento_Cliente`)
    REFERENCES `cine_colombia`.`Persona` (`Nombre_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Boleta_Cartelera1`
    FOREIGN KEY (`Cartelera_Nombre_Pelicula`)
    REFERENCES `cine_colombia`.`Cartelera` (`Nombre_Pelicula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Boleta_Sala1`
    FOREIGN KEY (`Sala_Numero_Sala`)
    REFERENCES `cine_colombia`.`Sala` (`Numero_Sala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
